-- Seed all QM test masters (idempotent)
INSERT INTO `test_masters` (`code`, `name`, `category`, `isCode`, `description`) VALUES
  ('SOIL-GSA', 'Grain Size Analysis', 'Soil', 'IS 2720 (Part 4)', 'Sieve analysis of soil — % passing each sieve, fines content.'),
  ('SOIL-LL', 'Liquid Limit (Casagrande)', 'Soil', 'IS 2720 (Part 5)', 'One-point method: LL = w × (N/25)^0.121'),
  ('SOIL-PLPI', 'Plastic Limit & Plasticity Index', 'Soil', 'IS 2720 (Part 5)', 'PL from thread-rolling test; PI = LL − PL.'),
  ('SOIL-SP', 'Standard Proctor (MDD/OMC)', 'Soil', 'IS 2720 (Part 7)', 'Light compaction — 5-point moisture-density curve.'),
  ('SOIL-MP', 'Modified Proctor (MDD/OMC)', 'Soil', 'IS 2720 (Part 8)', 'Heavy compaction — 5-point moisture-density curve.'),
  ('SOIL-SR', 'Field Density — Sand Replacement', 'Soil', 'IS 2720 (Part 28)', 'In-situ dry density by sand replacement; degree of compaction vs MDD.'),
  ('SOIL-CC', 'Field Density — Core Cutter', 'Soil', 'IS 2720 (Part 29)', 'In-situ dry density by core cutter; degree of compaction vs MDD.'),
  ('SOIL-CBR', 'Laboratory CBR', 'Soil', 'IS 2720 (Part 16)', 'CBR at 2.5mm & 5.0mm penetration (soaked).'),
  ('SOIL-FSI', 'Free Swell Index', 'Soil', 'IS 2720 (Part 40)', 'Swelling potential of soil.'),
  ('AGG-SIEVE', 'Sieve Analysis', 'Aggregate', 'IS 2386 (Part 1)', 'Gradation of coarse/fine aggregate.'),
  ('AGG-AIV', 'Aggregate Impact Value', 'Aggregate', 'IS 2386 (Part 4)', 'Resistance to sudden impact.'),
  ('AGG-ACV', 'Aggregate Crushing Value', 'Aggregate', 'IS 2386 (Part 4)', 'Resistance to crushing under gradually applied load.'),
  ('AGG-LAA', 'Los Angeles Abrasion Value', 'Aggregate', 'IS 2386 (Part 4)', 'Resistance to abrasion.'),
  ('AGG-FI', 'Flakiness Index', 'Aggregate', 'IS 2386 (Part 1)', 'Shape test — flaky particles.'),
  ('AGG-EI', 'Elongation Index', 'Aggregate', 'IS 2386 (Part 1)', 'Shape test — elongated particles.'),
  ('AGG-WA', 'Water Absorption', 'Aggregate', 'IS 2386 (Part 3)', 'Water absorption of aggregate.'),
  ('AGG-SG', 'Specific Gravity', 'Aggregate', 'IS 2386 (Part 3)', 'Specific gravity & water absorption (pycnometer/wire basket).'),
  ('BIT-PEN', 'Penetration Test', 'Bitumen', 'IS 1203', 'Penetration at 25°C (0.1 mm units).'),
  ('BIT-SP', 'Softening Point (Ring & Ball)', 'Bitumen', 'IS 1205', 'Softening point temperature.'),
  ('BIT-DUC', 'Ductility Test', 'Bitumen', 'IS 1208', 'Ductility at 27°C.'),
  ('BIT-VIS', 'Viscosity Test', 'Bitumen', 'IS 1206', 'Absolute viscosity at 60°C (poise).'),
  ('BIT-FF', 'Flash & Fire Point', 'Bitumen', 'IS 1209', 'Flash and fire point (Cleveland open cup).'),
  ('BIT-SG', 'Specific Gravity (Bitumen)', 'Bitumen', 'IS 1202', 'Specific gravity at 27°C (pycnometer).'),
  ('MIX-MARSHALL', 'Marshall Stability & Flow', 'Bituminous Mix', 'MS-2 (Asphalt Institute)', 'Stability (kN) and flow (mm) of compacted specimens.'),
  ('MIX-BINDER', 'Binder Content (Extraction)', 'Bituminous Mix', 'ASTM D2172', 'Bitumen content by centrifuge extraction.'),
  ('MIX-VOIDS', 'Air Voids / VMA / VFB', 'Bituminous Mix', 'MS-2', 'Volumetrics from Gmb, Gmm, aggregate & binder gravities.'),
  ('MIX-CORE', 'Field Density — Core (Bituminous)', 'Bituminous Mix', 'ASTM D2726', 'Core density vs Marshall/lab density — degree of compaction.'),
  ('CONC-CUBE', 'Cube Compressive Strength (7/28 day)', 'Concrete', 'IS 516 (Part 1)', '150 mm cubes — individual & mean strength.'),
  ('CONC-SLUMP', 'Slump Test', 'Concrete', 'IS 1199 (Part 2)', 'Workability — measured slump vs specified range.'),
  ('CEM-FIN', 'Fineness (Dry Sieving)', 'Cement', 'IS 4031 (Part 1)', 'Residue on 90 micron sieve.'),
  ('CEM-CONS', 'Standard Consistency', 'Cement', 'IS 4031 (Part 4)', 'Water % for 33–35 mm Vicat plunger penetration (2-trial interpolation).'),
  ('CEM-SET', 'Initial & Final Setting Time', 'Cement', 'IS 4031 (Part 5)', 'Vicat apparatus — time from adding water.'),
  ('CEM-SND', 'Soundness (Le Chatelier)', 'Cement', 'IS 4031 (Part 3)', 'Expansion of cement paste.'),
  ('CEM-STR', 'Compressive Strength (Mortar Cubes)', 'Cement', 'IS 4031 (Part 6)', '70.6 mm mortar cubes at 28 days.'),
  ('STL-TEN', 'Tensile / Yield / Elongation', 'Steel', 'IS 1608 / IS 1786', 'Yield stress, tensile strength, % elongation.'),
  ('STL-BEND', 'Bend Test', 'Steel', 'IS 1599', '180° bend around specified mandrel — visual check for cracks.'),
  ('STL-WT', 'Weight per Metre', 'Steel', 'IS 1786', 'Unit weight vs nominal (tolerance check).'),
  ('SOIL-FCBR', 'Field CBR', 'Soil', 'IS 2720 (Part 31)', 'In-situ CBR from proving-ring loads at 2.5mm & 5.0mm penetration.'),
  ('SOIL-PLT', 'Plate Load Test', 'Soil', 'IS 1888', 'Safe bearing capacity from load at 25mm settlement; modulus of subgrade reaction.'),
  ('SOIL-BB', 'Benkelman Beam Deflection', 'Soil', 'IRC 81', 'Rebound deflection — characteristic Dc = mean + 2σ.'),
  ('SOIL-NMC', 'Natural Moisture Content', 'Soil', 'IS 2720 (Part 2)', 'Oven-dry method — record value (indicative).'),
  ('SOIL-MCC', 'Moisture Content at Compaction', 'Soil', 'IS 2720 (Part 2)', 'Field MC vs OMC — within ±2% of OMC.'),
  ('SOIL-THK', 'Layer Thickness Check', 'Soil', 'MoRTH (field check)', 'Mean ≥ design; no point > 5mm below design.'),
  ('AGG-SE', 'Sand Equivalent Test', 'Aggregate', 'IS 2720 / ASTM D2419', 'Cleanliness of fine aggregate.'),
  ('BIT-STRIP', 'Stripping Test', 'Bitumen', 'IS 6241', 'Visual stripping after 24h immersion — ≤ 5%.'),
  ('BIT-ER', 'Elastic Recovery', 'Bitumen', 'IRC SP 53', 'For PMB/CRMB — ≥ 50% recovery.'),
  ('BIT-EMR', 'Emulsion — Residue by Evaporation', 'Bitumen', 'IS 8887', 'Binder content of bitumen emulsion.'),
  ('BIT-EMV', 'Emulsion — Viscosity (Saybolt Furol)', 'Bitumen', 'IS 8887', 'Flow time at 50°C.'),
  ('BIT-PRIME', 'Rate of Spread — Prime Coat', 'Bitumen', 'MoRTH 502', 'Tray test — kg/sqm.'),
  ('BIT-TACK', 'Rate of Spread — Tack Coat', 'Bitumen', 'MoRTH 503', 'Tray test — kg/sqm.'),
  ('CONC-FB', 'Beam Flexural Strength', 'Concrete', 'IS 516 (Part 2)', 'Third-point loading — fb = PL/bd².'),
  ('CONC-RH', 'Rebound Hammer (NDT)', 'Concrete', 'IS 13311 (Part 2)', 'Indicative strength estimate — not for acceptance.'),
  ('CONC-UPV', 'Ultrasonic Pulse Velocity (NDT)', 'Concrete', 'IS 13311 (Part 1)', 'Concrete quality grading — indicative.'),
  ('CONC-WQ', 'Water Quality for Concrete', 'Concrete', 'IS 456', 'Mixing/curing water chemical limits.')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `category` = VALUES(`category`), `isCode` = VALUES(`isCode`), `description` = VALUES(`description`);
